---
- name: check if Oracle SQL Developer archive is present
  stat:
    path: "{{ ferrarimarco_oracle_sql_dev_archive_path }}"
    register: sqldeveloper_archive
  failed_when: false

- name: create install directory
  file:
    dest: "{{ ferrarimarco_oracle_sql_dev_install_dir }}"
    state: directory
  when: sqldeveloper_archive.stat.exists == True

- name: unpack archive from master
  unarchive:
    creates: "{{ ferrarimarco_oracle_sql_dev_install_dir ~ '/sqldeveloper/sqldeveloper.sh' }}"
    dest: "{{ ferrarimarco_oracle_sql_dev_install_dir }}"
    src: "{{ ferrarimarco_oracle_sql_dev_archive_path }}"
  when: sqldeveloper_archive.stat.exists == True
